"""empty message

Revision ID: b778c67c15d3
Revises: 
Create Date: 2025-11-15 14:17:56.186608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b778c67c15d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index('ix_cash_status_status_name', 'cash_status', ['status_name'], unique=False)
    op.create_table('cash_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index('ix_cash_type_type_name', 'cash_type', ['type_name'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('cash_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cash_type'], ['cash_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index('ix_category_category_name', 'category', ['category_name'], unique=False)
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_utc', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cash_status', sa.Integer(), nullable=False),
    sa.Column('cash_type', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cash_status'], ['cash_status.id'], ),
    sa.ForeignKeyConstraint(['cash_type'], ['cash_type.id'], ),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_flow_cash_status', 'cash_flow', ['cash_status'], unique=False)
    op.create_index('ix_cash_flow_cash_type', 'cash_flow', ['cash_type'], unique=False)
    op.create_index('ix_cash_flow_category', 'cash_flow', ['category'], unique=False)
    op.create_index('ix_cash_flow_create_utc', 'cash_flow', ['create_utc'], unique=False)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(), nullable=False),
    sa.Column('parent_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_name')
    )
    op.create_index('ix_subcategory_subcategory_name', 'subcategory', ['subcategory_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subcategory_subcategory_name', table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index('ix_cash_flow_create_utc', table_name='cash_flow')
    op.drop_index('ix_cash_flow_category', table_name='cash_flow')
    op.drop_index('ix_cash_flow_cash_type', table_name='cash_flow')
    op.drop_index('ix_cash_flow_cash_status', table_name='cash_flow')
    op.drop_table('cash_flow')
    op.drop_index('ix_category_category_name', table_name='category')
    op.drop_table('category')
    op.drop_index('ix_cash_type_type_name', table_name='cash_type')
    op.drop_table('cash_type')
    op.drop_index('ix_cash_status_status_name', table_name='cash_status')
    op.drop_table('cash_status')
    # ### end Alembic commands ###
